<?php $this->layout_Class()->contentWrapper('col2r')?>

<div class="content">
	<header class="menu">
		<h2>Twoje projekty</h2>
<?php if($this->oUser->hasPrivilege(Privileges::PROJ_CRATE)):?>
		<a href="/project/adm/add">+nowy projekt</a>
<?php endif;?>
		<div class="clear"></div>
	</header>
	<div>
	<?php foreach($this->oPaginator as $oItem):?>
		<article>
			<h4><?php echo $oItem->getName()?> </h4>
			<p>
				<?php echo $oItem->getDesc()?>
			</p>
			<p>
				<a href="/project/summary/index/id/<?php echo $oItem->getId() ?>">przejdź do projektu</a>
			<?php if($this->oUser->hasPrivilege(Privileges::PROJ_ADM, $oItem->getId())): ?>
				|
				<a href="/project/adm/edit/id/<?php echo $oItem->getId() ?>">edytuj projekt</a> |
				<a href="/project/groups/list/id/<?php echo $oItem->getId() ?>">zarządzaj grupami</a> |
				<a href="#/project/adm/delete/id/<?php echo $oItem->getId() ?>" class="confirm" data-confirm="Czy na pewno chcesz usunąć ten projekt?">usuń projekt</a>
			<?php endif;?>
			</p>
		</article>
	<?php endforeach;?>

		<?php echo $this->paginationControl(
					$this->oPaginator,
					'Sliding',
					'paginator.phtml',
					array(
						'pname'		=> 'page',
						'pcount'	=> 6,
						'actionUrl'	=> '/project/index/index'
					)
		);?>
	</div>
</div>
<?php echo $this->sidebar_Project()?>