<!DOCTYPE html>
<html dir="ltr" lang="pl">
<head>
	<title>Tinab</title>
	<meta charset="utf-8" />
	<link rel="stylesheet" media="projection, screen" href="/css/tinab.css" />
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>
<body>
	<header>
		<?php echo $this->mainPanel()?>
	</header>
	<div class="page-wrapper">
		<?php echo $this->flashMessenger(); ?>
		<div class="<?php echo $this->layoutClass()->contentWrapper()?>">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</body>
</html>
