<!DOCTYPE html>
<html dir="ltr" lang="pl">
<head>
	<title>Tinab</title>
	<meta charset="utf-8" />
	<link rel="stylesheet" media="projection, screen" href="/css/tinab.css" />
</head>
<body>
	<header>
		<h1><a href="/">Tinab</a></h1>
	</header>
	<div class="page-wrapper">
		<?php echo $this->flashMessenger(); ?>
		<div class="<?php echo $this->layoutClass()->contentWrapper()?>">
			<div class="content">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</div>
</body>
</html>