<form method="post" autocomplete="off" action="">

	<?php $sField = 'old_passwd';
	echo $this->form_Field(
		'stare hasło',
		$sField,
		$this->formPassword($sField)
	)?>

	<?php $sField = 'passwd';
	echo $this->form_Field(
		'nowe hasło',
		$sField,
		$this->formPassword($sField)
	)?>

	<?php $sField = 'passwd2';
	echo $this->form_Field(
		'powtórz nowe hasło',
		$sField,
		$this->formPassword($sField)
	)?>

	<button type="submit">zmień hasło</button>
</form>