<?php $this->layout_Class()->contentWrapper('login')?>

<header>
	<h2>Logowanie</h2>
</header>
<div>
	<form method="post" action="/">

		<?php $sField = 'email';
		echo $this->form_Field(
			'email',
			$sField,
			$this->formText($sField, $this->form_Value($sField))
		)?>

		<?php $sField = 'passwd';
		echo $this->form_Field(
			'hasło',
			$sField,
			$this->formPassword($sField, $this->form_Value($sField))
		)?>

		<?php $sField = 'remember';
		echo $this->form_Field(
			'Zapamiętaj mnie',
			$sField,
			$this->formCheckbox($sField, $this->form_Value($sField)),
			array('class' => 'remember'),
			array('flip' => true)
		)?>

		<button type="submit">zaloguj</button>
	</form>
</div>