<?php $this->layout_Class()->contentWrapper('col2r')?>

<div class="content">
	<header>
		<h2>Projekty - przydzielanie userów do grupy</h2>
	</header>
	<div>
		<h3><?php echo $this->oProject->getName() ?></h3>
		<p>
			<strong>grupa:</strong>
			<?php echo $this->oGroup->getName() ?>
		</p>
		<br />
		<form method="post" action="" autocomplete="off">
			<?php $sField = 'users';
			echo $this->form_Field(
				'Członkowie grupy',
				$sField,
				$this->form_MultiChoose($sField, $this->form_Value($sField, array()), array(), $this->aUsers)
			)?>
			<button type="submit">zapisz</button>
		</form>
	</div>
</div>

<?php echo $this->sidebar_Admin()?>