<?php $this->layoutClass()->contentWrapper('admin')?>

<div class="content">
	<header>
		<h2>Administracja - grupy</h2>
		<a href="/administration/groups-add">+nowa grupa</a>
		<div class="clear" />
	</header>
	<div>
		<?php foreach($this->oPaginator as $oItem):?>
		<article>
			<h4><?php echo $oItem->getName()?></h4>

			<p>
				<?php echo $oItem->getDescription()?>
			</p>
			<p>
				<strong>liczba użytkowników:</strong>
				<?php echo $oItem->getUsersCount()?>
				<strong>uprawnienia:</strong>
				<?php echo implode(',', $this->privilegesDesc($oItem->getPrivileges()))?>
			</p>
			<p>
				<a href="#">zobacz użytkowników</a> |
				<a href="#">dodaj użytkownika</a> |
				<a href="#">edytuj grupę</a> |
				<a href="#">usuń grupę</a>
			</p>
		</article>
		<?php endforeach;?>

		<?php echo $this->paginationControl(
					$this->oPaginator,
					'Sliding',
					'app-partials/paginator.phtml',
					array(
						'pname'		=> 'page',
						'pcount'	=> 6,
						'actionUrl'	=> '/administration/groups'
					)
		);?>
	</div>
</div>
<?php echo $this->sidebarAdmin()?>