<?php $this->layout_Class()->contentWrapper('admin')?>

<div class="content">
	<header class="menu">
		<h2>Administracja - grupy</h2>
		<a href="/administration/groups-add">+nowa grupa</a>
		<div class="clear"></div>
	</header>
	<div>
		<?php foreach($this->oPaginator as $oItem):?>
		<article>
			<h4><?php echo $oItem->getName()?></h4>

			<p>
				<?php echo $oItem->getDescription()?>
			</p>
			<p>
				<strong>liczba użytkowników:</strong>
				<?php echo $oItem->getUsersCount()?>
				<strong>uprawnienia:</strong>
				<?php echo implode(', ', $this->privilegesDesc($oItem->getPrivileges()))?>
			</p>
			<p>
				<a href="/administration/groups-users/id/<?php echo $oItem->getId() ?>">edytuj użytkowników</a> |
				<a href="/administration/groups-edit/id/<?php echo $oItem->getId() ?>">edytuj grupę</a> |
				<a href="#/administration/groups-delete/id/<?php echo $oItem->getId() ?>" class="confirm" data-confirm="Czy na pewno chcesz usunąć tą grupę?">usuń grupę</a>
			</p>
		</article>
		<?php endforeach;?>

		<?php echo $this->paginationControl(
					$this->oPaginator,
					'Sliding',
					'app-partials/paginator.phtml',
					array(
						'pname'		=> 'page',
						'pcount'	=> 6,
						'actionUrl'	=> '/administration/groups'
					)
		);?>
	</div>
</div>
<?php echo $this->sidebar_Admin()?>