<?php
	$this->layout_Class()->contentWrapper('col2r');

	$this->headScript()->appendFile('/js/lib/Model.js')
						->appendFile('/js/lib/Factory.js')
						->appendFile('/js/models/User.js')
						->appendFile('/js/models/Env.js')
						->appendFile('/js/models/Task.js')
						->appendFile('/js/models/TaskFactory.js')
						->appendFile('/js/tasks.js')
						->appendFile('/js/taskEditE.js')
						->callJs('Lib_Factory.setProjectId', $this->oProject->getId());
?>

<div class="content">
	<header class="menu">
		<h2>Projekt: </h2>
		<?php echo $this->oProject->getName() ?>
		<a> | wg środowiska</a>
		<a href="/project/tasks/index/id/<?php echo $this->oProject->getId()?>">wg realizacji</a>
		<div class="clear"></div>
	</header>
	<div>
		<form class="task-add-form hide" action="#" method="post">
			<label for="task">Zadanie</label>
			<input type="text" id="task" name="task" /><br />

			<label for="labels">Etykiety</label>
			<input type="text" id="labels" name="labels"/>
			<br />

			<label for="users">Dla kogo</label>
			<?php echo $this->formSelect('users', '', null, array('' => '-- wszyscy --') + $this->aUsers)?>
			<br />

			<button type="submit">Dodaj</button>
			<a href="#" class="task-close">anuluj</a>
		</form>
			<h2>Brak środowiska</h2>
			<ul class="task-list none">
		<?php foreach($this->aTasks as $oTask):?>
			<?php if(null == $oTask->getEnvId()):?>
					<li>
						<input type="checkbox" class="task" data-id="<?php echo $oTask->getId()?>" />
						<span class="task-env"><?php echo $this->task_Status($oTask->getStatus()) ?></span>

						<?php foreach($oTask->getTags() as $sTag):?>
							<span class="task-label"><?php echo $sTag?></span>
						<?php endforeach;?>

						<span class="task"><?php echo $oTask->getTask() ?></span>

						<?php if($oTask->getRespUserId() !== null):?>
							<span class="task-user"><?php echo $this->aUsers[$oTask->getRespUserId()]?></span>
						<?php endif;?>

						<a class="task-edit" href="/project/tasks/edit/id/<?php echo $this->oProject->getId()?>/task/<?php echo $oTask->getId()?>">
						Edytuj
						</a>
						<a class="task-del" href="#" data-id="<?php echo $oTask->getId()?>">
						Usuń
						</a>
					</li>
			<?php endif;?>
		<?php endforeach;?>
			</ul>

		<?php foreach($this->aEnvs as $iEnv => $sEnv):?>
			<h2><?php echo $sEnv ?></h2>
				<ul class="task-list <?php echo $iEnv?>">
			<?php foreach($this->aTasks as $oTask):?>
				<?php if($iEnv == $oTask->getEnvId()):?>
						<li>
							<input type="checkbox" class="task" data-id="<?php echo $oTask->getId()?>" />
							<span class="task-env"><?php echo $this->task_Status($oTask->getStatus()) ?></span>

							<?php foreach($oTask->getTags() as $sTag):?>
								<span class="task-label"><?php echo $sTag?></span>
							<?php endforeach;?>

							<span class="task"><?php echo $oTask->getTask() ?></span>

							<?php if($oTask->getRespUserId() !== null):?>
								<span class="task-user"><?php echo $this->aUsers[$oTask->getRespUserId()]?></span>
							<?php endif;?>

							<a class="task-edit" href="/project/tasks/edit/id/<?php echo $this->oProject->getId()?>/task/<?php echo $oTask->getId()?>">
							Edytuj
							</a>
						</li>
				<?php endif;?>
			<?php endforeach;?>
			</ul>
		<?php endforeach;?>
	</div>
</div>
<ul class="hide">
	<li>
		<span class="task-env"></span>
		<span class="task-label"></span>
		<span class="task"><?php echo $oTask->getTask() ?></span>

		<?php if($oTask->getRespUserId() !== null):?>
			<span class="task-user"><?php echo $this->aUsers[$oTask->getRespUserId()]?></span>
		<?php endif;?>

		<a class="task-edit" href="/project/tasks/edit/id/<?php echo $this->oProject->getId()?>/task/<?php echo $oTask->getId()?>">
		Edytuj
		</a>
	</li>
</ul>

<?php echo $this->sidebar_Task()?>




