<h2>Projekt: </h2><?php echo $this->oProject->getName() ?>

<p>
 TUTAJ SPIS (tylko kilka pierwszych) ZADAŃ AKTUALNEGO USERA (z podziałem na środowiska i statusy)
 <br />
 (tutaj linki do pełnego spisu zdań)
</p>

<p>
 TUTAJ SPIS ZADAŃ (kilka pierwszych)  NIE PRZYDZIELONYCH NIKOMU
 <br />
 (tutaj linki do pełnego spisu nowych zdań)
</p>

<p>
 TUTAJ SPIS FUNKCJONALNOŚCI JESZCZE NIE WPROWADZONYCH NA PRODUKCJĘ
</p>

<p>
 TUTAJ SPIS WSPÓPŁRACOWNIKÓW
</p>



